Logic and ui for restaurant website with responsive tab navigations
dannisonarias/Restaurant-App pull request #1
Opened 2020-06-05 00:41 UTC by dannisonarias

create a webpack environment with all configurations and directories
create a barebones HTML file
create modules for each tab
create tab-switching logic inside of index.js

2020-06-05 15:28 UTC, dannisonarias commented
This linter is not working properly with es6 and scss . It doesn't even allow me to use self invoked functions.  TSE please review the project as it is , and if you have issues with the linter , please help me fix the issues don't just point them out.  i know they are there .

2020-06-06 16:51 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hi Team! 

Great job with this project! It's a cool looking cafe! 😄 

***You only have to address some minor required changes (see review comments)***

All you have to do now I guess is address the minor issues and we should be fine!
Let's get these minor issues sorted! 😄 👍 

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-06 16:51 UTC, mcrd25 commented on .stickler.yml
> +    config: ./sass-lint.yml
Concerning your sass lint issues:
This file does not exist. it should be your `.stylelintrc.json` not so?
Maybe this should help. Once your config is right it should be fine.

2020-06-06 16:51 UTC, mcrd25 commented on .stickler.yml
> +    config: ./sass-lint.yml
Also, You did not even have to style lint. but since you did it's best to fix errors.

2020-06-06 16:51 UTC, mcrd25 commented on .stickler.yml
> +    config: ./sass-lint.yml
If fixing the config here does not help I'd try my best to help troubleshoot with you. 🙂

2020-06-06 16:51 UTC, mcrd25 commented on README.md
> +Feel free to check the [issues page](https://github.com/dannisonarias/Javascript_Tic_Tac_Toe/issues).
This is linking to another project's issues page. Please fix.

2020-06-06 16:51 UTC, mcrd25 commented on README.md
> +## Usage
[OPTIONAL]
Consider adding how to actually run the app.

2020-06-06 16:51 UTC, mcrd25 commented on README.md
> +This project is [MIT](./license.md) licensed.
Good README. 😄

2020-06-06 16:51 UTC, mcrd25 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Your README references `build` script but you don't actually have build script which uses your webpack commands

2020-06-06 16:51 UTC, mcrd25 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Scripts like `build`, `start`, and `development` are required according to this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from pathright.

2020-06-09 21:30 UTC, bellom approved these changes
## Hi @dannisonarias  :clap: 

**Great work making all the necessary corrections from the previous review.**

**NOTE:** Make sure to always set up your linter's config and you should have your linter's check on your `GitHub` page.
checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
![image](https://user-images.githubusercontent.com/31897434/63073279-0e393680-bf20-11e9-9c84-f142caf1e675.png)
If you are not having this check on your `Github` page, kindly visit :point_right:[ linter set up](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-12 14:36 UTC, merged